name: pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    run-on: ubuntu-latest
    steps:
    - name: checkout file
      uses: actions/checkout@v1
    - name: run script
      run: echo Hello world
